development:
  adapter: mysql2
  encoding: utf8
  database: reactions
  username: root
  password: none
  host: 0.0.0.0
  port: 3306

test:
  adapter: mysql2
  database: ":memory:"
  timeout: 500

production:
  adapter: mysql2
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
